### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by nickdesaulniers** [ucsb-seclab/difuze#15]
I just finished reading your paper and wanted to let you know that I really enjoyed it.

I work on building the Linux kernel with Clang (and other LLVM utilities) full time at Google, via a project called ClangBuiltLinux: https://clangbuiltlinux.github.io/

I see you paper was published in 2017; the irony was that we had a patch set for building Pixel 1's kernel w/ Clang, but didn't end up shipping a Clang built kernel until Pixel 2 (2017, the same year as your paper).

Looks like some commits here show you already know about building kernels with Clang.  Just wanted to say thanks for the research and if you hit any bugs compiling your kernels w/ Clang, please let us know.

(I also happened to speak with someone (Michael Spectre) this week who was looking to add the approach you describe to syzkaller; I must have found your paper from his design doc).

**Comment by jcorina** [comment]
Hey, thanks for reaching out and saying hello. Glad you enjoyed the paper :)
I'm curious, is the design doc you mention public?
We'll be sure to reach out if we have any compilation issues in the future.

**Comment by nickdesaulniers** [comment]
> I'm curious, is the design doc you mention public?

I think it's internal only, but maybe unintentionally.  I'll ask him if he can share.
