### ISSUE TITLE
run_all.py error ......

### ISSUE THREAD

**Issue by Riverhac** [ucsb-seclab/difuze#3]
Hi,
    when i use `python run_all.py -l ~/mediatek_kernel/llvm_bitcode_out -a 1 -m ~/mediatek_kernel/kernel-3.18/makeout.txt -g aarch64-linux-android-gcc -n 2 -o ~/mediatek_kernel/kernel-3.18/out -k ~/mediatek_kernel/kernel-3.18 -f ~/mediatek_kernel/ioctl_finder_out` command line follow RADME.I allways get a lot of error log :

/home/user/mediatek_kernel/kernel-3.18/out/../arch/arm64/crypto/aes-modes.S:486:2: note: while in macro instantiation 
 do_decrypt_block2x
 ^
<instantiation>:3:2: error: instruction requires: crypto         //<---------------------- error                                                     
 aesd v1.16b, v23.16b
 ^
<instantiation>:4:2: note: while in macro instantiation                                                               
 do_enc_Nx d, imc, v23, v0, v1, , 
 ^
<instantiation>:3:2: note: while in macro instantiation                                                               
 round_Nx d, v23, v0, v1, , 
 ^
<instantiation>:8:7: note: while in macro instantiation                                                               
2222: .irp key, v21, v22, v23, v24, v25, v26, v27, v28, v29
      ^
<instantiation>:1:1: note: while in macro instantiation                                                               
do_block_Nx d, w3, v0, v1
^
<instantiation>:1:1: note: while in macro instantiation                                                               
decrypt_block2x v0, v1, w3, x2, x6, w7
^
/home/user/mediatek_kernel/kernel-3.18/out/../arch/arm64/crypto/aes-modes.S:486:2: note: while in macro instantiation 
 do_decrypt_block2x
 ^
<instantiation>:9:2: error: instruction requires: crypto                                                              
 aesimc v0.16b, v0.16b
 ^
<instantiation>:4:2: note: while in macro instantiation                                                               
 do_enc_Nx d, imc, v23, v0, v1, , 
 ^
<instantiation>:3:2: note: while in macro instantiation                                                               
 round_Nx d, v23, v0, v1, , 
 ^
<instantiation>:8:7: note: while in macro instantiation                                                               
2222: .irp key, v21, v22, v23, v24, v25, v26, v27, v28, v29
      ^
<instantiation>:1:1: note: while in macro instantiation                                                               
do_block_Nx d, w3, v0, v1
^
<instantiation>:1:1: note: while in macro instantiation                                                               
decrypt_block2x v0, v1, w3, x2, x6, w7
^
/home/user/mediatek_kernel/kernel-3.18/out/../arch/arm64/crypto/aes-modes.S:486:2: note: while in macro instantiation 
 do_decrypt_block2x
 ^
<instantiation>:11:2: error: instruction requires: crypto                                                             
 aesimc v1.16b, v1.16b
 ^

....

What's the effect of this？
thank you.

**Comment by Machiry** [comment]
Clang fails to compile certain .S files. It is okay and expected; In practice it should not affect the tool.
