### ISSUE TITLE
How do I use difuze with syzkaller?

### ISSUE THREAD

**Issue by nclman** [ucsb-seclab/difuze#5]
Any instructions available?

**Comment by srikanth007m** [comment]
Yes, There are no instructions available on how to use difuze with syzkaller. Seems the maintainer is not active.

**Comment by Machiry** [comment]
Sorry Guys, I will update the details here in a couple of days.

**Comment by jcorina** [comment]
Sorry, the syzkaller extension will not be released, that is left as an exercise to the reader :)

**Comment by srikanth007m** [comment]
@jcorina - Seeing the results of Difuze with syzkaller is more promising than running Difuze alone. That is the reason i am looking to give it a try of Difuze plugin with syzkaller to see the interesting bugs out of the combination.
